ALTER TABLE events ADD COLUMN title VARCHAR(100) NOT NULL;
ALTER TABLE events RENAME COLUMN adress TO address;
ALTER TABLE events ALTER COLUMN address TYPE TEXT;
ALTER TABLE events ALTER COLUMN sport TYPE INT USING sport::integer;